name: betterbrick
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.2.0
  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  rxdart: ^0.27.3
  timezone: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 800

  assets:
    - images/

